export const PGTEXT: string = 
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. In cursus at lectus sit amet consectetur. Morbi a neque nec diam pharetra varius. Proin ac leo nec risus bibendum efficitur ac quis ipsum. Aenean faucibus bibendum turpis, ac scelerisque tortor ornare pretium. Mauris pellentesque gravida quam blandit condimentum. Quisque non sapien dui. Praesent vel massa sit amet sem hendrerit efficitur. Fusce auctor risus ut porttitor mollis. Phasellus dolor eros, ullamcorper quis lectus vel, suscipit rutrum nunc. Quisque vitae turpis egestas, semper enim eu, tristique metus. Aliquam sit amet neque quis velit sagittis euismod dictum nec purus. Praesent feugiat erat velit, in suscipit lectus maximus vitae." +
"  Proin eu lorem tincidunt est pellentesque ullamcorper ut non eros. Proin consequat, enim ut ornare sagittis, urna nulla blandit velit, vulputate mattis lectus nisl non turpis. Cras iaculis ligula ac maximus sagittis. Cras varius imperdiet augue, id varius massa ullamcorper non. Nulla facilisi. Fusce maximus vitae nisi vel blandit. In consectetur egestas maximus. Morbi ultricies augue nec mi placerat, vel pellentesque nisl convallis. Donec viverra molestie nisi pellentesque iaculis. Nullam ut tortor neque. Sed quis mollis nisi." 
+
"  Donec pulvinar arcu id lacinia iaculis. Sed fermentum pharetra feugiat. Donec gravida nisl ut lectus placerat, ut gravida nulla porta. Quisque tristique arcu eu metus tincidunt, vitae lobortis enim tristique. In tellus est, ullamcorper ut tempus sit amet, pellentesque sit amet felis. Etiam porta, sapien at finibus ultrices, ipsum est lobortis nulla, in tincidunt urna elit vitae tortor. Nunc interdum erat vitae orci ultrices, eu lobortis urna mollis. Cras finibus turpis in tristique tempor. Suspendisse eu commodo leo, eget posuere dui. Curabitur a tortor diam. Fusce mollis gravida ullamcorper." +
"  Curabitur efficitur iaculis felis. Nam vitae accumsan ipsum. Maecenas a nisl feugiat, tincidunt dui et, lobortis leo. Quisque sit amet facilisis eros. Suspendisse vehicula ex sed nulla convallis tempor. Duis sit amet justo non nibh vulputate tincidunt quis ac purus. Mauris pellentesque laoreet nunc sit amet placerat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sit amet tellus in lorem gravida tristique vel sit amet ex. Ut turpis quam, molestie non vehicula sed, consequat sed mauris. Praesent magna magna, sollicitudin at sollicitudin sit amet, aliquam non ante. Mauris nunc eros, gravida quis aliquet in, facilisis ullamcorper dolor. Curabitur eleifend et elit ac rhoncus. Nullam ac tincidunt nisl. Vestibulum imperdiet sed orci id consectetur. Vestibulum mauris tortor, laoreet a mi eget, volutpat laoreet purus." +
" Maecenas nunc metus, ultrices commodo turpis sit amet, pharetra vulputate ligula. Fusce porttitor ut ex eget fermentum. Ut volutpat dolor quis ligula blandit, id tempus ex interdum. Mauris iaculis sem ut purus volutpat tincidunt. Nulla ut tellus vitae orci pulvinar aliquam. Integer vitae odio nec purus tempus mattis. Mauris vitae sapien in arcu vestibulum laoreet." 

export const PGTEXTODD: string = 
"This is the even page of the story.  The Ionic Story, My Ionic Story.  This is just a story and is not a real historic event.  This is just to display on a screen.  If you want to read more you will have to write it yourself.  The thing is the story has no characters and that will always be a problem for a story.  This is going to be short because it is a short story.  Actually, it is a really short story. " 
